// Generated by scripts/build-provenance.mjs
export const BUILD_INFO = {
  "version": "0.11.0-alpha.22",
  "sourceHash": "56ea8be79c6a6b94579c9c47f0260583ac9d311b133ed6c0dc86a2b11ee89f99",
  "builtAt": "2026-10-03T04:29:29.766Z",
  "fileCount": 190
} as const;
