import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {afterEach,it,expect} from "vitest";
import {executeDocumentFormat} from "../../src/tools/document-format.js";
import {executeDocumentVerify} from "../../src/tools/document-verify.js";
import {executeSourcesExcel,findPython,hashDocument} from "../../src/tools/sources-to-excel.js";
import {documentProcess} from "../../src/tools/local-document-process.js";
const roots:string[]=[];
afterEach(async()=>{for(const root of roots.splice(0))await fs.rm(root,{recursive:true,force:true});});
async function fixture(){const cwd=await fs.mkdtemp(path.join(os.tmpdir(),"ally-format-"));roots.push(cwd);await fs.writeFile(path.join(cwd,"source.csv"),"ID,amount\n00123,1280.50");return {cwd,timeoutMs:60000};}
const request={output:"结果/报告.docx",sources:["source.csv"],title:"数据汇总报告",summary:"源表记录 00123，金额 1280.50。",sections:[{heading:"数据",paragraphs:["按原始记录核对"],tables:[{headers:["编号","金额"],rows:[["00123","1280.50"]]}]}],attachments:["数据说明"],issuer:"测试组",date:"2026年9月21日",contact:"测试人员"};
it("writes structured content with mandatory formatting, traceability and no overwrite",async()=>{
 const ctx=await fixture();const result=await executeDocumentFormat({action:"build",request},ctx);
 expect(result.isError).toBe(false);expect(result.metadata?.documentArtifact?.verification.profileDeclarations).toBe("passed");
 const audit=JSON.parse(await fs.readFile(path.join(ctx.cwd,request.output+".audit.json"),"utf8"));
 expect(audit.profile).toMatchObject({bodySizePt:16,bodyLinePt:28,titleSizePt:22,titleLinePt:30,titleBlankLines:2,marginTopCm:3.7});
 expect(audit.sources[0].sha256).toBe(await hashDocument(path.join(ctx.cwd,"source.csv")));
 await expect(executeDocumentVerify({path:request.output,sources:request.sources,expectedText:["00123","1280.50","附件：数据说明"],minTables:1},ctx)).resolves.toMatchObject({isError:false});
 await expect(executeDocumentFormat({action:"build",request},ctx)).rejects.toThrow("不能覆盖");
 await expect(executeDocumentFormat({action:"build",request:{...request,output:"../outside.docx"}},ctx)).rejects.toThrow("outside");
});
it("adds blank lines only after the main title and converts Word table evidence into a real workbook",async()=>{
 const ctx=await fixture();await executeDocumentFormat({action:"build",request},ctx);
 const python=await findPython(ctx,["docx","openpyxl"]);if(!python?.ready)throw new Error("Test prerequisite: docx/openpyxl");
 const paragraphs=JSON.parse(await documentProcess(python.command,[...python.args,"-I","-X","utf8","-c","import json,sys;from docx import Document;d=Document(sys.argv[1]);print(json.dumps([{'text':p.text,'style':p.style.name} for p in d.paragraphs],ensure_ascii=False))",request.output],ctx));
 expect(paragraphs.slice(0,4).map((p:{text:string})=>p.text)).toEqual([request.title,"","",request.summary]);
 const heading=paragraphs.findIndex((p:{style:string})=>p.style==="Heading 1");
 expect(paragraphs[heading+1].text).toBe("按原始记录核对");
 await executeSourcesExcel({action:"scan",request:{inputs:[request.output],output:"scan/manifest.json"}},ctx);
 const manifest=JSON.parse(await fs.readFile(path.join(ctx.cwd,"scan/manifest.json"),"utf8"));
 const source=manifest.files[0],row=source.segments.find((s:{kind?:string;values?:string[]})=>s.kind==="table_row"&&s.values?.[0]==="00123");
 expect(row.values).toEqual(["00123","1280.50"]);
 expect(row.cells[0]).toMatchObject({colspan:1,vmerge:null});
 const evidence=(quote:string)=>[{file_id:source.id,locator:row.locator,quote}];
 const result=await executeSourcesExcel({action:"build",request:{manifest:"scan/manifest.json",output:"结果/转换.xlsx",coverage:{[source.id]:{status:"included",review_note:"本测试核对指定表格两列；不声明整篇报告语义转换"}},sheets:[{name:"数据",rowMeaning:"一行代表一个编号的金额",designReason:"原文同一实体的编号与金额配对为两列",columns:[{key:"id",header:"编号",type:"text"},{key:"amount",header:"金额",type:"decimal"}],rows:[{values:{id:"00123",amount:"1280.50"},evidence:{id:evidence("00123"),amount:evidence("1280.50")}}]}]}},ctx);
 expect(result.isError).toBe(false);
 const cells=JSON.parse(await documentProcess(python.command,[...python.args,"-I","-c","import json;from openpyxl import load_workbook;w=load_workbook('结果/转换.xlsx');s=w.active;print(json.dumps([s['A2'].value,s['B2'].value,s['A2'].data_type]));w.close()"],ctx));
 expect(cells).toEqual(["00123",1280.5,"s"]);
});
it("never skips a textless PDF page; only matching full-page OCR can reconstruct editable text",async()=>{
 const ctx=await fixture();const python=await findPython(ctx,["pypdf"]);if(!python?.ready)throw new Error("Test prerequisite: pypdf");
 await documentProcess(python.command,[...python.args,"-I","-c","from pypdf import PdfWriter;w=PdfWriter();w.add_blank_page(width=595,height=842);w.write('scan.pdf')"],ctx);
 const conversion={path:"scan.pdf",output:"converted.docx"};
 await expect(executeDocumentFormat({action:"pdf_to_word",request:conversion},ctx)).rejects.toThrow("第 1 页");
 const ocr={source:"scan.pdf",sha256:await hashDocument(path.join(ctx.cwd,"scan.pdf")),method:"paddleocr-vl",totalPages:1,processedPages:[1],segments:[{page:1,text:"扫描件回归测试 00123"}]};
 await fs.writeFile(path.join(ctx.cwd,"ocr.json"),JSON.stringify({...ocr,sha256:"wrong"}));
 await expect(executeDocumentFormat({action:"pdf_to_word",request:{...conversion,ocr:["ocr.json"]}},ctx)).rejects.toThrow("不匹配");
 await fs.writeFile(path.join(ctx.cwd,"ocr.json"),JSON.stringify(ocr));
 const result=await executeDocumentFormat({action:"pdf_to_word",request:{...conversion,ocr:["ocr.json"]}},ctx);
 expect(JSON.parse(result.content)).toMatchObject({layoutRestored:false,totalPages:1,ocrPages:[1]});
 await expect(executeDocumentVerify({path:"converted.docx",sources:["scan.pdf"],expectedText:["扫描件回归测试 00123","原始版式"]},ctx)).resolves.toMatchObject({isError:false});
});
it("preserves mixed table structures and requires a per-sheet design before writing Word-derived data",async()=>{
 const ctx=await fixture();
 const mixed={...request,sections:[...request.sections,{heading:"事项",paragraphs:["与金额数据属于不同记录粒度"],tables:[{headers:["事项","负责人","状态"],rows:[["复核","张三","待办"]]}]}]};
 await executeDocumentFormat({action:"build",request:mixed},ctx);
 await executeSourcesExcel({action:"scan",request:{inputs:[request.output],output:"scan/manifest.json"}},ctx);
 const manifest=JSON.parse(await fs.readFile(path.join(ctx.cwd,"scan/manifest.json"),"utf8")),source=manifest.files[0];
 expect(source.structure.tables.map((t:{columnCounts:number[]})=>t.columnCounts)).toEqual([[2],[3]]);
 const segment=source.segments.find((s:{values?:string[]})=>s.values?.[0]==="复核");
 const fields=["事项","负责人","状态"],values=["复核","张三","待办"];
 const sheet={name:"行动事项",columns:fields.map(key=>({key,header:key,type:"text"})),rows:[{values:Object.fromEntries(fields.map((key,i)=>[key,values[i]])),evidence:Object.fromEntries(fields.map((key,i)=>[key,[{file_id:source.id,locator:segment.locator,quote:values[i]}]]))}]};
 const req={manifest:"scan/manifest.json",output:"结果/事项.xlsx",coverage:{[source.id]:{status:"partial",reason:"此回归用例只提取行动事项，金额表未纳入",review_note:"按独立表格来源核对"}},sheets:[sheet]};
 await expect(executeSourcesExcel({action:"build",request:req},ctx)).rejects.toThrow("rowMeaning");
 const result=await executeSourcesExcel({action:"build",request:{...req,sheets:[{...sheet,rowMeaning:"一行一项待办",designReason:"事项不同于金额统计，保留负责人和状态而不混合金额列"}]}},ctx);
 expect(result.isError).toBe(false);
 const audit=JSON.parse(await fs.readFile(path.join(ctx.cwd,"结果/事项.xlsx.audit.json"),"utf8"));
 expect(audit.request.sheets[0].columns.map((c:{key:string})=>c.key)).toEqual(fields);
 expect(audit.request.sheets[0].rowMeaning).toBe("一行一项待办");
 expect(audit.result.unresolved_files).toContain(source.id);
});
it("repairs only the initial title spacing in a new copy, preserving tables, images and all other ZIP parts",async()=>{
 const ctx=await fixture();await executeDocumentFormat({action:"build",request},ctx);
 const python=await findPython(ctx,["docx"]);if(!python?.ready)throw new Error("docx missing");
 const prepare="from docx import Document;from io import BytesIO;import base64;d=Document('结果/报告.docx');[d.paragraphs[1]._element.getparent().remove(d.paragraphs[1]._element) for _ in range(2)];d.add_picture(BytesIO(base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a2ioAAAAASUVORK5CYII=')));d.save('old.docx')";
 await documentProcess(python.command,[...python.args,"-I","-X","utf8","-c",prepare],ctx);
 const hash=await hashDocument(path.join(ctx.cwd,"old.docx"));
 const result=await executeDocumentFormat({action:"title_spacing",request:{path:"old.docx",output:"fixed.docx"}},ctx);
 expect(result.isError).toBe(false);expect(result.metadata?.documentArtifact?.verification).toMatchObject({images:1,tables:1});
 expect(await hashDocument(path.join(ctx.cwd,"old.docx"))).toBe(hash);
 const inspect="from zipfile import ZipFile;from lxml import etree as E;from docx import Document;a=ZipFile('old.docx');b=ZipFile('fixed.docx');assert a.namelist()==b.namelist();assert all(a.read(n)==b.read(n) for n in a.namelist() if n!='word/document.xml');x=E.fromstring(a.read('word/document.xml'));y=E.fromstring(b.read('word/document.xml'));ns={'w':'http://schemas.openxmlformats.org/wordprocessingml/2006/main'};body=y.find('w:body',ns);[body.remove(body[1]) for _ in range(2)];assert E.tostring(x)==E.tostring(y);print('unchanged_except_two_blank_paragraphs')";
 expect(await documentProcess(python.command,[...python.args,"-I","-X","utf8","-c",inspect],ctx)).toContain("unchanged_except_two_blank_paragraphs");
});
